(let [x (sample (normal 0 1))
      z (sample (categorical [3 4 5]))]
  (if (> x 0)
    (if (< z 1)
      (observe (normal 0.5 1) 1)
      (observe (normal 2 1) 1))
    (if (> z -1)
      (observe (normal -0.5 1) 1)
      (observe (normal -2 1) 1)))
  x)